//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinForm_OtoGaleri_Projesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayit
    {
        public int Personel_Kullanici_ID { get; set; }
        public string Personel_KullaniciAd { get; set; }
        public string Personel_Sifre { get; set; }
        public string Personel_TcNo { get; set; }
        public string Personel_AdSoyad { get; set; }
    }
}
