//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinForm_OtoGaleri_Projesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Arac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Arac()
        {
            this.Tbl_İslemler = new HashSet<Tbl_İslemler>();
        }
    
        public int Arac_ID { get; set; }
        public string Arac_Fiyat { get; set; }
        public string Arac_Adet { get; set; }
        public string Arac_Marka { get; set; }
        public string Arac_Model { get; set; }
        public string Arac_Yil { get; set; }
        public string Sanziman { get; set; }
        public decimal Motor_Hacmi { get; set; }
        public string Arac_Yakit { get; set; }
        public string Arac_Paket { get; set; }
        public string Arac_Renk { get; set; }
        public string Arac_Km { get; set; }
        public int Sube_ID { get; set; }
        public int Arac_Durumu_ID { get; set; }
    
        public virtual Tbl_Arac_Durumu Tbl_Arac_Durumu { get; set; }
        public virtual Tbl_Sube Tbl_Sube { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_İslemler> Tbl_İslemler { get; set; }
    }
}
