//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinForm_OtoGaleri_Projesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_İslemler
    {
        public int Islem_ID { get; set; }
        public string Islem_Tarihi { get; set; }
        public decimal Islem_Fiyati { get; set; }
        public int Musteri_ID { get; set; }
        public int Arac_ID { get; set; }
        public int Personel_ID { get; set; }
    
        public virtual Tbl_Arac Tbl_Arac { get; set; }
        public virtual Tbl_Musteri Tbl_Musteri { get; set; }
        public virtual Tbl_Personel Tbl_Personel { get; set; }
    }
}
