//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinForm_OtoGaleri_Projesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Personel()
        {
            this.Tbl_İslemler = new HashSet<Tbl_İslemler>();
        }
    
        public int Personel_ID { get; set; }
        public string Personel_Ad_Soyad { get; set; }
        public string Personel_Yas { get; set; }
        public string Personel_TcNo { get; set; }
        public string Personel_Mail { get; set; }
        public string Personel_Telefon { get; set; }
        public int Sube_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_İslemler> Tbl_İslemler { get; set; }
        public virtual Tbl_Sube Tbl_Sube { get; set; }
    }
}
